"""Service-area pages.

These exist for local search ("deck builder Mt Lebanon PA") and for answer
engines that need to know, concretely, where this contractor works. Each page
carries real local detail — housing stock, terrain, permitting authority — so
it earns the ranking instead of being a doorway page with a swapped town name.
"""

AREAS = [
    {
        "slug": "pittsburgh",
        "name": "Pittsburgh",
        "county": "Allegheny County",
        "meta_title": "General Contractor in Pittsburgh, PA | Osas Construction",
        "meta_desc": "Licensed general contractor serving every Pittsburgh neighborhood — remodeling, roofing, siding, concrete, decks, landscaping, junk removal and snow. (412) 923-2092.",
        "h1": "General Contractor in Pittsburgh, PA",
        "answer": "Osas Construction Group is a licensed, insured general contractor based in Pittsburgh, PA, working across all city neighborhoods from Lawrenceville and Bloomfield to Brookline, Beechview and the North Side. Services include remodeling, roofing, siding, concrete, decks, landscaping, junk removal and snow removal. Call or text (412) 923-2092.",
        "intro": [
            "Pittsburgh is a city of old, well-built, complicated houses. Brick rowhouses sharing party walls in Lawrenceville and the South Side. Four-squares and Victorians in Highland Park and Friendship. Frame houses clinging to a 30% grade in Beechview and Mount Washington. Post-war brick capes in Brookline and Carrick.",
            "Almost none of it is square, level or standard. Plaster over lath, balloon framing, cast iron drains, knob-and-tube remnants, coal chutes bricked over, additions built by four different owners across a century — that is the normal condition of the work here.",
            "We quote for what is actually there. That means walking the property, opening a closet ceiling if we need to, and telling you where we expect surprises before you sign anything.",
        ],
        "local": [
            ("Permits", "Work inside city limits goes through the Department of Permits, Licenses and Inspections (PLI). Historic districts add a review step. We handle the applications."),
            ("Access", "Narrow streets, alley-only access, shared driveways and steep grades all change how material gets to a job. It is in our estimate, not a surprise charge."),
            ("Party walls", "Rowhouse work touches the neighbor's structure. We plan around that rather than discovering it during demo."),
        ],
        "projects": [
            "Kitchen and bathroom gut renovations in pre-war homes",
            "Plaster repair, drywall and full interior repaints",
            "Roof replacement and seamless gutters on steep city roofs",
            "Retaining walls and concrete steps on hillside lots",
            "Rear decks and porch rebuilds",
            "Basement and attic cleanouts with same-day hauling",
            "Sidewalk, step and driveway replacement",
            "Winter plowing and salting for city businesses",
        ],
        "neighborhoods": [
            "Lawrenceville", "Bloomfield", "Shadyside", "Squirrel Hill", "Highland Park",
            "Point Breeze", "Greenfield", "South Side", "Mount Washington", "Brookline",
            "Beechview", "Carrick", "Brighton Heights", "North Side", "Polish Hill",
            "Garfield", "Regent Square", "Stanton Heights", "Sheraden", "Hazelwood",
        ],
        "faqs": [
            ("Do you work in every Pittsburgh neighborhood?",
             "Yes — city-wide, from the East End to the South Hills slopes to the North Side. Access and parking vary a lot by neighborhood, and we account for that when we quote."),
            ("Do you pull City of Pittsburgh permits?",
             "Yes. Permitted work in the city goes through PLI, and we handle the application and inspections as part of the contract."),
        ],
    },
    {
        "slug": "mount-lebanon",
        "name": "Mt. Lebanon",
        "county": "Allegheny County",
        "meta_title": "Contractor in Mt. Lebanon, PA | Osas Construction Group",
        "meta_desc": "Remodeling, roofing, masonry and deck contractor serving Mt. Lebanon, PA. Licensed, insured, experienced with 1920s brick homes. Free estimate: (412) 923-2092.",
        "h1": "Contractor in Mt. Lebanon, PA",
        "answer": "Osas Construction Group serves Mt. Lebanon, PA with kitchen and bathroom remodeling, drywall and plaster repair, roofing, masonry, decks and landscaping. Mt. Lebanon's 1920s and 1930s brick homes need a contractor comfortable with plaster, slate and tile roofs, and mature-tree drainage. Call or text (412) 923-2092.",
        "intro": [
            "Mt. Lebanon's housing stock is largely inter-war: brick Tudors, center-hall colonials and foursquares built in the 1920s and 1930s along the trolley lines, with mature trees and deep-rooted landscaping around them.",
            "Those houses are wonderful and specific. Plaster walls that crack at predictable places. Original clay tile and slate roofs that have been patched by six different roofers. Detached single-car garages down a shared driveway. Beautiful woodwork nobody wants damaged during a remodel.",
            "We work carefully in them — dust containment through finished space, protection over original floors, and finish work that matches the trim profiles already in the house.",
        ],
        "local": [
            ("Plaster, not drywall", "Most original walls are plaster over lath. We repair plaster and blend drywall into it so the transition does not telegraph."),
            ("Mature tree canopy", "Heavy leaf load means gutters fill fast and lawns go thin under shade. Both are routine here."),
            ("Municipal permits", "Mt. Lebanon issues its own building permits and inspections. We file for your project."),
        ],
        "projects": [
            "Kitchen remodels that open a small 1920s kitchen to the dining room",
            "Bathroom gut-and-rebuilds with tile showers",
            "Plaster repair, skim coating and whole-house interior painting",
            "Roof replacement, flashing and seamless gutters",
            "Brick repointing, chimney repair and stone steps",
            "Rear decks, porch rebuilds and railings",
            "Fall leaf removal and seasonal cleanups",
            "Driveway replacement and concrete walkways",
        ],
        "neighborhoods": ["Virginia Manor", "Beverly Heights", "Sunset Hills", "Mission Hills", "Washington Road corridor", "Uptown Mt. Lebanon"],
        "faqs": [
            ("Do you have experience with older Mt. Lebanon homes?",
             "Yes — plaster walls, original trim, steam and hot water heat, knob-and-tube remnants and tile roofs are all normal conditions in this part of the South Hills, and we price for them rather than being surprised by them."),
            ("Can you match existing trim and moldings?",
             "In most cases yes. Matching or closely reproducing original profiles matters in these houses, and we would rather do that than install a stock profile that looks wrong next to the original."),
        ],
    },
    {
        "slug": "bethel-park",
        "name": "Bethel Park",
        "county": "Allegheny County",
        "meta_title": "Contractor in Bethel Park, PA | Osas Construction Group",
        "meta_desc": "Remodeling, siding, roofing, concrete and deck contractor serving Bethel Park, PA. Licensed and insured. Free estimate: (412) 923-2092.",
        "h1": "Contractor in Bethel Park, PA",
        "answer": "Osas Construction Group serves Bethel Park, PA with remodeling, siding and roofing replacement, concrete driveways, decks, basement finishing and landscaping. Bethel Park's post-war ranches and splits are now at the age where original siding, roofs and kitchens all need replacing. Call or text (412) 923-2092.",
        "intro": [
            "Bethel Park grew with the post-war South Hills: ranches, split-levels and colonials on generous lots, most built between the 1950s and the 1970s.",
            "Those homes are hitting the age where the original aluminum or early vinyl siding is chalking, the second-generation roof is at the end of its life, and the kitchen has been remodeled exactly once, in 1988.",
            "That is straightforward, high-value work — siding and roofing replacement, kitchen and bath updates, deck rebuilds and concrete driveways — on houses that are structurally sound and easy to work on.",
        ],
        "local": [
            ("Siding replacement", "1960s aluminum and first-generation vinyl are both past due. Tear-off often reveals missing house wrap."),
            ("Basements", "Full basements under most splits and ranches — finishing them is one of the most common requests here."),
            ("Driveways", "Wide, flat driveways from the same era that are now scaling and cracking from decades of freeze-thaw."),
        ],
        "projects": [
            "Vinyl and fiber cement siding replacement",
            "Roof replacement with new gutters and downspouts",
            "Kitchen and bathroom remodeling",
            "Basement finishing and egress work",
            "Concrete driveway and sidewalk replacement",
            "Composite deck rebuilds",
            "Lawn maintenance, mulch and seasonal cleanups",
            "Driveway plowing and salting in winter",
        ],
        "neighborhoods": ["Village of Eastgate", "South Park Line", "Broughton Road corridor", "Library", "Hoodridge"],
        "faqs": [
            ("Do you replace siding on split-level homes?",
             "Yes, and they are extremely common here. Splits have more corners, more transitions and more flashing details than a simple two-story, which is where an inexperienced siding job leaks."),
            ("Can you finish a basement in Bethel Park?",
             "Yes — framing, insulation, drywall, flooring, lighting and egress. We check for moisture first, because finishing over a damp wall just hides the problem behind new drywall."),
        ],
    },
    {
        "slug": "upper-st-clair",
        "name": "Upper St. Clair",
        "county": "Allegheny County",
        "meta_title": "Contractor in Upper St. Clair, PA | Osas Construction",
        "meta_desc": "Kitchen, bath and whole-home remodeling plus decks, patios and hardscaping in Upper St. Clair, PA. Licensed and insured. (412) 923-2092.",
        "h1": "Contractor in Upper St. Clair, PA",
        "answer": "Osas Construction Group serves Upper St. Clair, PA with kitchen and bathroom remodeling, whole-home renovation, composite decks, paver patios, retaining walls and drainage work. Larger homes on wooded, sloped lots make outdoor living projects and water management the most common requests here. Call (412) 923-2092.",
        "intro": [
            "Upper St. Clair is larger homes on larger, often wooded and sloped lots — mostly built from the 1970s onward, with a steady stream of 1980s and 1990s colonials now due for their first serious kitchen and bath renovation.",
            "The outdoor work here is the interesting part. Sloped rear yards mean multi-level decks, retaining walls and paver patios cut into grade, and all of it lives or dies on drainage.",
        ],
        "local": [
            ("Sloped lots", "Terracing, retaining walls and stepped patios instead of a single flat pad."),
            ("Wooded properties", "Heavy leaf load on gutters, shade that will not support turf, and root systems to work around."),
            ("Larger scopes", "Whole-floor renovations and full outdoor living builds rather than single-room touch-ups."),
        ],
        "projects": [
            "Kitchen renovations with layout changes",
            "Primary bathroom remodels with tile showers",
            "Multi-level composite decks and railings",
            "Paver patios, fire pits and outdoor kitchens",
            "Retaining walls with engineered drainage",
            "French drains, regrading and downspout burial",
            "Roofing and skylight replacement",
            "Landscape design, planting and lighting",
        ],
        "neighborhoods": ["Boyce", "Mayview", "Hays Road corridor", "McLaughlin Run", "Trotwood Hills"],
        "faqs": [
            ("Can you build a deck and patio on a steep back yard?",
             "Yes — that is the normal condition here. It usually becomes a combination: a deck off the house, steps down, and a paver patio cut into the slope behind a retaining wall, with drainage behind the wall."),
            ("Do you design outdoor living spaces as well as build them?",
             "Yes. Landscape design, plant selection and hardscape layout are part of what we do, and keeping design and construction with one contractor avoids the usual finger-pointing."),
        ],
    },
    {
        "slug": "peters-township",
        "name": "Peters Township",
        "county": "Washington County",
        "meta_title": "Contractor in Peters Township & McMurray, PA | Osas",
        "meta_desc": "Remodeling, decks, patios, landscaping and concrete in Peters Township and McMurray, PA. Licensed, insured contractor. Free estimate: (412) 923-2092.",
        "h1": "Contractor in Peters Township & McMurray, PA",
        "answer": "Osas Construction Group serves Peters Township and McMurray, PA with remodeling, composite decks, paver patios, outdoor kitchens, concrete and landscaping. Peters Township's newer subdivisions on larger lots make outdoor living and basement finishing the most requested projects. Call or text (412) 923-2092.",
        "intro": [
            "Peters Township and McMurray are newer than most of what we work on — subdivisions largely built from the 1990s onward, on generous lots, with builder-grade finishes now a couple of decades old.",
            "The work follows from that: builder decks reaching the end of their life and being rebuilt in composite, unfinished basements getting finished, builder kitchens getting real cabinets and stone counters, and back yards getting the patio the builder never installed.",
        ],
        "local": [
            ("Washington County", "Permitting runs through Peters Township rather than an Allegheny County municipality; we file accordingly."),
            ("Builder-grade upgrades", "Twenty-year-old builder finishes are the most common starting point."),
            ("Large yards", "Room for real hardscaping, irrigation and landscape design."),
        ],
        "projects": [
            "Composite deck rebuilds and railing upgrades",
            "Paver patios, fire pits and outdoor kitchens",
            "Basement finishing with bathrooms and wet bars",
            "Kitchen and primary bath remodeling",
            "Concrete driveway extensions and walkways",
            "Irrigation installation and landscape design",
            "Lawn programs and seasonal cleanups",
            "Snow plowing for driveways and lots",
        ],
        "neighborhoods": ["McMurray", "Venetia", "Valleybrook", "Hidden Valley", "Brush Run"],
        "faqs": [
            ("Do you work outside Allegheny County?",
             "Yes — Peters Township, McMurray and the surrounding Washington County communities are part of our regular service area."),
            ("Can you replace a builder deck with composite?",
             "Yes, and it is one of the most common projects in these neighborhoods. If the framing and footings are sound we can often reuse the structure and replace decking and railings, which saves considerable cost."),
        ],
    },
    {
        "slug": "robinson-township",
        "name": "Robinson Township",
        "county": "Allegheny County",
        "meta_title": "Contractor in Robinson Township, PA | Osas Construction",
        "meta_desc": "Remodeling, roofing, siding, concrete and commercial property services in Robinson Township, PA. Licensed and insured. Free estimate: (412) 923-2092.",
        "h1": "Contractor in Robinson Township, PA",
        "answer": "Osas Construction Group serves Robinson Township, PA with residential remodeling, roofing, siding, concrete and decks, plus commercial fit-outs, lot maintenance and snow removal along the Robinson retail corridor. Call or text (412) 923-2092 for a free estimate.",
        "intro": [
            "Robinson Township is two kinds of work in one municipality. There is the residential side — a mix of mid-century homes and newer plans on hillside lots — and there is the retail and office corridor around the mall and Settlers Ridge.",
            "We do both: kitchen and bath work and exterior replacement for homeowners, and build-outs, parking lot maintenance, pressure washing and snow contracts for commercial property.",
        ],
        "local": [
            ("Hillside lots", "Retaining walls, drainage and stepped access are common on the residential side."),
            ("Commercial corridor", "Tenant fit-outs, storefront maintenance and seasonal snow contracts."),
            ("Highway access", "Easy staging and material delivery from the Parkway West."),
        ],
        "projects": [
            "Kitchen and bathroom remodeling",
            "Roof and siding replacement",
            "Retaining walls and hillside drainage",
            "Concrete driveways, curbs and walkways",
            "Commercial tenant fit-outs and interior renovation",
            "Parking lot plowing, salting and pressure washing",
            "Junk removal and property cleanouts",
            "Grounds maintenance contracts",
        ],
        "neighborhoods": ["North Fayette line", "Settlers Ridge area", "Montour Run corridor", "Kennedy Township line", "Moon line"],
        "faqs": [
            ("Do you take commercial contracts in Robinson?",
             "Yes — fit-outs, interior renovation, exterior repairs, pressure washing, grounds maintenance and seasonal snow contracts, all insured with a certificate available for your management company."),
            ("Do you clear commercial lots before opening hours?",
             "That is the standard arrangement for a seasonal snow contract. We set the target clear time when the contract is written."),
        ],
    },
    {
        "slug": "moon-township",
        "name": "Moon Township",
        "county": "Allegheny County",
        "meta_title": "Contractor in Moon Township, PA | Osas Construction Group",
        "meta_desc": "Home remodeling, roofing, siding, decks and commercial services in Moon Township, PA. Licensed, insured contractor. Free estimate: (412) 923-2092.",
        "h1": "Contractor in Moon Township, PA",
        "answer": "Osas Construction Group serves Moon Township, PA with remodeling, roofing, siding, decks, concrete and landscaping for homeowners, plus commercial build-outs and property maintenance near the airport corridor. Call or text (412) 923-2092 for a free estimate.",
        "intro": [
            "Moon Township spans a wide range: 1960s and 1970s homes in the older plans, newer construction toward the airport corridor, and a substantial commercial and hospitality presence around the business park.",
            "Residential work here is mostly replacement-cycle — roofs, siding, windows, kitchens and baths — with deck and patio projects on the larger lots.",
        ],
        "local": [
            ("Airport corridor", "Hotel, office and retail property maintenance and renovation."),
            ("Replacement cycle", "Homes from the 1960s–1990s reaching their second roof and first major interior remodel."),
            ("Mature plans", "Established trees mean gutter volume and shade-lawn problems."),
        ],
        "projects": [
            "Roof replacement and seamless gutters",
            "Siding, soffit and fascia replacement",
            "Kitchen and bathroom remodeling",
            "Deck and porch rebuilds",
            "Concrete driveways, steps and walkways",
            "Landscape maintenance and cleanups",
            "Commercial interior renovation and fit-outs",
            "Snow plowing and ice management",
        ],
        "neighborhoods": ["Coraopolis Heights", "Thorn Run", "Beaver Grade corridor", "Crescent line", "University Boulevard area"],
        "faqs": [
            ("Do you serve the airport-area business parks?",
             "Yes — commercial interior work, exterior repairs, pressure washing, grounds maintenance and seasonal snow contracts."),
            ("Is Moon Township within your standard service area?",
             "Yes, with no travel surcharge for standard projects."),
        ],
    },
    {
        "slug": "cranberry-township",
        "name": "Cranberry Township",
        "county": "Butler County",
        "meta_title": "Contractor in Cranberry Township, PA | Osas Construction",
        "meta_desc": "Decks, patios, basement finishing, remodeling and landscaping in Cranberry Township, PA. Licensed and insured contractor. (412) 923-2092.",
        "h1": "Contractor in Cranberry Township, PA",
        "answer": "Osas Construction Group serves Cranberry Township, PA with composite decks, paver patios, basement finishing, kitchen and bath remodeling, concrete and landscaping. Cranberry's newer subdivisions mean outdoor living upgrades and builder-grade replacements are the most common projects. Call (412) 923-2092.",
        "intro": [
            "Cranberry is one of the fastest-grown parts of the region, and the housing reflects it: large subdivisions built from the mid-1990s onward, on sites that were farmland within living memory.",
            "That produces a specific set of projects. Builder decks at end of life. Unfinished basements. Back yards with no patio and, frequently, drainage that was never quite right after the development graded the site.",
        ],
        "local": [
            ("Butler County", "Permitting and inspections run through Cranberry Township; we file for the project."),
            ("Graded subdivisions", "Post-development grading often leaves water sitting where it should not. Drainage work is common."),
            ("Newer stock", "Builder-grade finishes at the 20–25 year replacement mark."),
        ],
        "projects": [
            "Composite deck rebuilds and expansions",
            "Paver patios, fire pits and outdoor kitchens",
            "Basement finishing with full baths",
            "Kitchen and bathroom remodeling",
            "Yard drainage, French drains and regrading",
            "Concrete patios and walkways",
            "Landscape design, planting and irrigation",
            "Driveway plowing and salting",
        ],
        "neighborhoods": ["Park Place", "Freedom Road corridor", "Route 228 area", "Graham Park area", "Seven Fields line"],
        "faqs": [
            ("Do you travel to Butler County?",
             "Yes — Cranberry Township, Seven Fields and the surrounding communities are in our regular service area."),
            ("Why does my new-ish yard hold water?",
             "Usually grading. Subdivision sites are cut and filled during development, and compacted fill plus a shallow topsoil layer drains badly. Regrading, a French drain or downspout burial normally solves it."),
        ],
    },
    {
        "slug": "wexford-pine-township",
        "name": "Wexford & Pine Township",
        "county": "Allegheny County",
        "meta_title": "Contractor in Wexford & Pine Township, PA | Osas",
        "meta_desc": "Remodeling, decks, patios, drainage and landscaping in Wexford and Pine Township, PA. Licensed, insured contractor. Free estimate: (412) 923-2092.",
        "h1": "Contractor in Wexford & Pine Township, PA",
        "answer": "Osas Construction Group serves Wexford and Pine Township, PA with kitchen and bath remodeling, composite decks, paver patios, retaining walls, drainage and landscaping. Wooded, sloped North Hills lots make water management a routine part of the work. Call (412) 923-2092.",
        "intro": [
            "Wexford and Pine Township are larger homes on wooded, rolling lots in the North Allegheny area, mostly built from the 1980s onward with a steady stream of newer construction.",
            "Heavy tree cover and real topography define the exterior work: gutters that fill fast, lawns that will not grow in shade, and back yards that need terracing before they can be used.",
        ],
        "local": [
            ("Wooded lots", "Gutter cleaning, leaf removal and shade-tolerant planting are recurring needs."),
            ("Rolling terrain", "Retaining walls, stepped patios and drainage rather than flat pads."),
            ("Larger homes", "Bigger scopes — full-floor renovations and complete outdoor living builds."),
        ],
        "projects": [
            "Kitchen and primary bathroom renovations",
            "Multi-level composite decks with lighting",
            "Paver patios, retaining walls and fire pits",
            "French drains, regrading and erosion control",
            "Roofing, gutters and gutter cleaning",
            "Landscape design and planting for shade",
            "Basement finishing",
            "Seasonal cleanups and snow removal",
        ],
        "neighborhoods": ["Wexford", "Pine Township", "Marshall Township line", "Franklin Park line", "Gibsonia line"],
        "faqs": [
            ("Do you handle drainage on sloped, wooded lots?",
             "Yes — French drains, catch basins, regrading, downspout burial and erosion control. On a wooded slope the water is usually coming from uphill, which changes where the solution goes."),
            ("Can you keep a lawn alive under heavy shade?",
             "Sometimes, with the right seed and aggressive overseeding. Often the better answer is converting the deepest shade to beds or ground cover rather than fighting it every year."),
        ],
    },
    {
        "slug": "shaler-ross-township",
        "name": "Shaler & Ross Township",
        "county": "Allegheny County",
        "meta_title": "Contractor in Shaler & Ross Township, PA | Osas",
        "meta_desc": "Roofing, siding, concrete, retaining walls and remodeling in Shaler and Ross Township, PA. Licensed and insured. Free estimate: (412) 923-2092.",
        "h1": "Contractor in Shaler & Ross Township, PA",
        "answer": "Osas Construction Group serves Shaler Township and Ross Township, PA with roofing, siding, concrete, retaining walls, remodeling and snow removal. North Hills hillside lots with steep driveways and aging retaining walls are routine work here. Call or text (412) 923-2092.",
        "intro": [
            "Shaler and Ross are classic North Hills: mid-century homes on hillside lots above the Allegheny, steep driveways, and retaining walls that were built when the plans went in and are now leaning.",
            "Failed walls, cracked driveways on a grade, and drainage running downhill into a basement are the three things we see most often up here — and they are usually the same problem in three forms.",
        ],
        "local": [
            ("Steep driveways", "Concrete on a grade needs correct thickness, reinforcement and drainage at the bottom, or it cracks and the garage floods."),
            ("Aging retaining walls", "Mid-century walls built without drainage behind them are failing all over the North Hills."),
            ("Winter grades", "Steep driveways are the hardest surfaces to keep safe in an ice event; salting matters as much as plowing."),
        ],
        "projects": [
            "Retaining wall replacement with proper drainage",
            "Concrete driveway replacement on grade",
            "Roof replacement, gutters and downspout rerouting",
            "Siding, soffit and fascia replacement",
            "Kitchen and bathroom remodeling",
            "French drains and basement water management from outside",
            "Deck and stair rebuilds on sloped lots",
            "Driveway plowing and ice management",
        ],
        "neighborhoods": ["Glenshaw", "Etna line", "Millvale line", "West View", "McKnight Road corridor", "Evergreen Hamlet area"],
        "faqs": [
            ("My retaining wall is leaning — can it be repaired or does it need replacing?",
             "A wall that is tipping or bulging has usually lost the argument with water pressure behind it, and cosmetic repair does not fix that. Replacement with drainage stone, filter fabric and a drain outlet is the durable answer. We will tell you honestly which one you are looking at."),
            ("Can you plow a steep driveway?",
             "Yes. Steep drives need salt and timing more than horsepower, which is why a seasonal contract works better than calling after the ice sets."),
        ],
    },
    {
        "slug": "monroeville",
        "name": "Monroeville",
        "county": "Allegheny County",
        "meta_title": "Contractor in Monroeville, PA | Osas Construction Group",
        "meta_desc": "Remodeling, roofing, siding, concrete and commercial services in Monroeville, PA. Licensed, insured contractor. Free estimate: (412) 923-2092.",
        "h1": "Contractor in Monroeville, PA",
        "answer": "Osas Construction Group serves Monroeville, PA with kitchen and bath remodeling, roofing, siding, concrete, decks and landscaping, plus commercial renovation and snow contracts along the Route 22 corridor. Call or text (412) 923-2092.",
        "intro": [
            "Monroeville is largely 1960s and 1970s development — split-levels, ranches and colonials on established lots — wrapped around one of the region's busiest commercial corridors.",
            "Residential work is replacement-cycle and modernization: second and third roofs, original siding, kitchens and baths that have not been touched since the houses were built. Commercial work along Business 22 runs to fit-outs, exterior repairs and winter contracts.",
        ],
        "local": [
            ("Split-levels", "More rooflines, more transitions and more flashing details than a simple two-story."),
            ("Mature lots", "Established trees, heavy leaf load and shade-thinned lawns."),
            ("Route 22 corridor", "Retail and office work, lot maintenance and seasonal snow."),
        ],
        "projects": [
            "Roof replacement on complex split-level rooflines",
            "Siding, soffit and fascia replacement",
            "Kitchen and bathroom remodeling",
            "Basement finishing",
            "Concrete driveways, patios and walkways",
            "Deck rebuilds and railing replacement",
            "Commercial tenant fit-outs and renovation",
            "Parking lot plowing and salting",
        ],
        "neighborhoods": ["Garden City", "Forest Hills line", "Pitcairn line", "Plum line", "Northern Pike corridor", "Miracle Mile area"],
        "faqs": [
            ("Do you serve the eastern suburbs beyond Monroeville?",
             "Yes — Penn Hills, Plum, Murrysville, Wilkins, Churchill, Forest Hills and the surrounding communities."),
            ("Do you handle commercial work along Route 22?",
             "Yes, including interior fit-outs, exterior repairs, pressure washing, grounds maintenance and seasonal snow contracts."),
        ],
    },
]

# Communities served without a dedicated page (rendered as links on the hub).
ALSO_SERVED = [
    "Carnegie", "Green Tree", "Scott Township", "Dormont", "Castle Shannon",
    "Whitehall", "Brentwood", "Baldwin", "Pleasant Hills", "Jefferson Hills",
    "South Park", "Bridgeville", "Canonsburg", "Coraopolis", "Kennedy Township",
    "Sewickley", "McCandless", "Franklin Park", "Gibsonia", "Hampton Township",
    "Fox Chapel", "Penn Hills", "Plum", "Murrysville", "Oakmont", "Verona",
    "Wilkinsburg", "Swissvale", "Forest Hills", "Churchill", "Etna", "Millvale",
    "Sharpsburg", "Bellevue", "Avalon", "Crafton", "Ingram", "Mt. Oliver",
    "West Mifflin", "Munhall", "Homestead", "McKeesport", "White Oak",
    "Seven Fields", "Mars", "Adams Township", "North Fayette", "Oakdale",
]
